<?php

/**
 * BaseFormu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $Items
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $Procedures
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getItems()       Returns the current record's "Items" collection
 * @method sfGuardUser         getAuthor()      Returns the current record's "Author" value
 * @method Doctrine_Collection getProcedures()  Returns the current record's "Procedures" collection
 * @method Formu               setId()          Sets the current record's "id" value
 * @method Formu               setUserId()      Sets the current record's "user_id" value
 * @method Formu               setName()        Sets the current record's "name" value
 * @method Formu               setDescription() Sets the current record's "description" value
 * @method Formu               setItems()       Sets the current record's "Items" collection
 * @method Formu               setAuthor()      Sets the current record's "Author" value
 * @method Formu               setProcedures()  Sets the current record's "Procedures" collection
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFormu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('formu');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item as Items', array(
             'refClass' => 'ItemFormu',
             'local' => 'form_id',
             'foreign' => 'item_id'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Procedure as Procedures', array(
             'local' => 'id',
             'foreign' => 'formu_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}