<?php

/**
 * BaseComunicationItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $revision_item_id
 * @property integer $author_id
 * @property string $subject
 * @property clob $message
 * @property sfGuardUser $Author
 * @property RevisionItem $RevisionItem
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getRevisionItemId()   Returns the current record's "revision_item_id" value
 * @method integer          getAuthorId()         Returns the current record's "author_id" value
 * @method string           getSubject()          Returns the current record's "subject" value
 * @method clob             getMessage()          Returns the current record's "message" value
 * @method sfGuardUser      getAuthor()           Returns the current record's "Author" value
 * @method RevisionItem     getRevisionItem()     Returns the current record's "RevisionItem" value
 * @method ComunicationItem setId()               Sets the current record's "id" value
 * @method ComunicationItem setRevisionItemId()   Sets the current record's "revision_item_id" value
 * @method ComunicationItem setAuthorId()         Sets the current record's "author_id" value
 * @method ComunicationItem setSubject()          Sets the current record's "subject" value
 * @method ComunicationItem setMessage()          Sets the current record's "message" value
 * @method ComunicationItem setAuthor()           Sets the current record's "Author" value
 * @method ComunicationItem setRevisionItem()     Sets the current record's "RevisionItem" value
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComunicationItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comunication_item');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('revision_item_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('author_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RevisionItem', array(
             'local' => 'revision_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}