<?php

/**
 * BaseRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $number
 * @property integer $parent_id
 * @property integer $procedure_id
 * @property integer $revision_state_id
 * @property integer $creator_id
 * @property boolean $block
 * @property clob $description
 * @property string $file
 * @property sfGuardUser $Creator
 * @property Procedure $Procedure
 * @property RevisionState $State
 * @property Doctrine_Collection $Items
 * @property Doctrine_Collection $Item
 * @property Doctrine_Collection $Revision
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getNumber()            Returns the current record's "number" value
 * @method integer             getParentId()          Returns the current record's "parent_id" value
 * @method integer             getProcedureId()       Returns the current record's "procedure_id" value
 * @method integer             getRevisionStateId()   Returns the current record's "revision_state_id" value
 * @method integer             getCreatorId()         Returns the current record's "creator_id" value
 * @method boolean             getBlock()             Returns the current record's "block" value
 * @method clob                getDescription()       Returns the current record's "description" value
 * @method string              getFile()              Returns the current record's "file" value
 * @method sfGuardUser         getCreator()           Returns the current record's "Creator" value
 * @method Procedure           getProcedure()         Returns the current record's "Procedure" value
 * @method RevisionState       getState()             Returns the current record's "State" value
 * @method Doctrine_Collection getItems()             Returns the current record's "Items" collection
 * @method Doctrine_Collection getItem()              Returns the current record's "Item" collection
 * @method Doctrine_Collection getRevisionItem()      Returns the current record's "RevisionItem" collection
 * @method Doctrine_Collection getRevision()          Returns the current record's "Revision" collection
 * @method Revision            setId()                Sets the current record's "id" value
 * @method Revision            setNumber()            Sets the current record's "number" value
 * @method Revision            setParentId()          Sets the current record's "parent_id" value
 * @method Revision            setProcedureId()       Sets the current record's "procedure_id" value
 * @method Revision            setRevisionStateId()   Sets the current record's "revision_state_id" value
 * @method Revision            setCreatorId()         Sets the current record's "creator_id" value
 * @method Revision            setBlock()             Sets the current record's "block" value
 * @method Revision            setDescription()       Sets the current record's "description" value
 * @method Revision            setFile()              Sets the current record's "file" value
 * @method Revision            setCreator()           Sets the current record's "Creator" value
 * @method Revision            setProcedure()         Sets the current record's "Procedure" value
 * @method Revision            setState()             Sets the current record's "State" value
 * @method Revision            setItems()             Sets the current record's "Items" collection
 * @method Revision            setItem()              Sets the current record's "Item" collection
 * @method Revision            setRevisionItem()      Sets the current record's "RevisionItem" collection
 * @method Revision            setRevision()          Sets the current record's "Revision" collectionItem
 * @property Doctrine_Collection $Revision
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getNumber()            Returns the current record's "number" value
 * @method integer             getParentId()          Returns the current record's "parent_id" value
 * @method integer             getProcedureId()       Returns the current record's "procedure_id" value
 * @method integer             getRevisionStateId()   Returns the current record's "revision_state_id" value
 * @method integer             getCreatorId()         Returns the current record's "creator_id" value
 * @method boolean             getBlock()             Returns the current record's "block" value
 * @method clob                getDescription()       Returns the current record's "description" value
 * @method string              getFile()              Returns the current record's "file" value
 * @method sfGuardUser         getCreator()           Returns the current record's "Creator" value
 * @method Procedure           getProcedure()         Returns the current record's "Procedure" value
 * @method RevisionState       getState()             Returns the current record's "State" value
 * @method Doctrine_Collection getItems()             Returns the current record's "Items" collection
 * @method Doctrine_Collection getItem()              Returns the current record's "Item" collection
 * @method Doctrine_Collection getRevisionItem()      Returns the current record's "RevisionItem" collection
 * @method Doctrine_Collection getRevision()          Returns the current record's "Revision" collection
 * @method Revision            setId()                Sets the current record's "id" value
 * @method Revision            setNumber()            Sets the current record's "number" value
 * @method Revision            setParentId()          Sets the current record's "parent_id" value
 * @method Revision            setProcedureId()       Sets the current record's "procedure_id" value
 * @method Revision            setRevisionStateId()   Sets the current record's "revision_state_id" value
 * @method Revision            setCreatorId()         Sets the current record's "creator_id" value
 * @method Revision            setBlock()             Sets the current record's "block" value
 * @method Revision            setDescription()       Sets the current record's "description" value
 * @method Revision            setFile()              Sets the current record's "file" value
 * @method Revision            setCreator()           Sets the current record's "Creator" value
 * @method Revision            setProcedure()         Sets the current record's "Procedure" value
 * @method Revision            setState()             Sets the current record's "State" value
 * @method Revision            setItems()             Sets the current record's "Items" collection
 * @method Revision            setItem()              Sets the current record's "Item" collection
 * @method Revision            setRevisionItem()      Sets the current record's "RevisionItem" collection
 * @method Revision            setRevision()          Sets the current record's "Revision" collection
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRevision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('revision');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('procedure_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('revision_state_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('creator_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('block', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'creator_id',
             'foreign' => 'id'));

        $this->hasOne('Procedure', array(
             'local' => 'procedure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RevisionState as State', array(
             'local' => 'revision_state_id',
             'foreign' => 'id'));

        $this->hasMany('Item as Items', array(
             'refClass' => 'RevisionItem',
             'local' => 'revision_id',
             'foreign' => 'item_id'));

        $this->hasMany('Item', array(
             'refClass' => 'RevisionItem',
             'local' => 'revision_id',
             'foreign' => 'item_id'));

        $this->hasMany('RevisionItem', array(
             'local' => 'id',
             'foreign' => 'revision_id'));

        $this->hasMany('ComunicationRevision as Revision', array(
             'local' => 'id',
             'foreign' => 'revision_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}