<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $group_id
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $Formus
 * @property sfGuardGroup $Group
 * @property Doctrine_Collection $Revisions
 * @property Doctrine_Collection $RevisionItem
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getGroupId()      Returns the current record's "group_id" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method clob                getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getFormus()       Returns the current record's "Formus" collection
 * @method sfGuardGroup        getGroup()        Returns the current record's "Group" value
 * @method Doctrine_Collection getRevisions()    Returns the current record's "Revisions" collection
 * @method Doctrine_Collection getRevisionItem() Returns the current record's "RevisionItem" collection
 * @method Item                setId()           Sets the current record's "id" value
 * @method Item                setGroupId()      Sets the current record's "group_id" value
 * @method Item                setTitle()        Sets the current record's "title" value
 * @method Item                setDescription()  Sets the current record's "description" value
 * @method Item                setFormus()       Sets the current record's "Formus" collection
 * @method Item                setGroup()        Sets the current record's "Group" value
 * @method Item                setRevisions()    Sets the current record's "Revisions" collection
 * @method Item                setRevisionItem() Sets the current record's "RevisionItem" collection
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Formu as Formus', array(
             'refClass' => 'ItemFormu',
             'local' => 'item_id',
             'foreign' => 'form_id'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('Revision as Revisions', array(
             'refClass' => 'RevisionItem',
             'local' => 'item_id',
             'foreign' => 'revision_id'));

        $this->hasMany('RevisionItem', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}