<?php

/**
 * CadastralData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class CadastralData extends BaseCadastralData
{

  public function __toString() {
    return $this->getCircunscripcion().' - '.$this->getSeccion().' - '.$this->getTipo().' - '.$this->getTipoNumero().' - '.$this->getParcela();
  }
}
