<?php

/**
 * ComunicationItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class ComunicationItem extends BaseComunicationItem {

  public function save(Doctrine_Connection $conn = null) {
    $singleton = sfContext::getInstance();
    $this->setAuthorId($singleton->getUser()->getGuardUser()->getId());
    parent::save($conn);
  }
}
