<?php

/**
 * Formu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Formu extends BaseFormu
{
  public function __toString() {
    $name = $this->get('name');
    return (isset($name)) ? $name : 'No definido !';
  }
}
