<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class Item extends BaseItem
{
  public function getGroupAcronym() {
    $words = explode(' ', $this->getGroup());
    $acronym = '';

    foreach ($words as $word) {
      if(strlen($word) > 2) {
        $acronym = $acronym.strtoupper(substr($word, 0, 1)).'. ';
      }
    }

    return $acronym;
  }
}
