<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString() {
    return $this->getCompleteName();
  }

  public function getCompleteName() {
    return $this->getProfile()->get('first_name').' '.$this->getProfile()->get('last_name');
  }
}
