<?php

/**
 * sfGuardGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Huemul
 * @subpackage model
 * @author     Damian Suarez
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
class sfGuardGroup extends PluginsfGuardGroup {

  public function getNameAcronym() {
    $words = explode(' ', $this->get('name'));
    $acronym = '';

    foreach ($words as $word) {
      if(strlen($word) > 2) {
        $acronym = $acronym.strtoupper(substr($word, 0, 1)).'. ';
      }
    }

    return $acronym;
  }

  public function getItems() {
    $q = Doctrine_Query::create()
      ->from('Item i')
      ->where('i.group_id = ?', $this->get('id'));
    return $q;
  }
}
