generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  Procedure
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 procedure
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:
        formu:                      { label: Formulario }
        
      list:
        fields:
          creator:                  { label: Professional }
          formu:                    { label: Formulario }
          revisions_count:          { label: R }
        display:                    [ creator, formu, cadastral_data, partida, revisions_count, _items, _state, dossier, _created_at, _updated_at ]
   
      filter:
        display:                    [ creator, formu_id, cadastral_data_id, dossier, state, revisions_count, created_at, updated_at, pendientes ]
      form: ~
      edit: ~ 
      new:     ~
